[TECHDEBT] Persistence Module, remove `DELETE` *actor* 'No-op' code
pokt-network/pocket pull request #238
Opened 2022-09-22 20:25 UTC by Olshansk

**IMPORTANT**: Please note that this is using #236 as the base branch.  IF #236 is merged before this, the base branch will need to be updated to main.

## Description

See the description in https://github.com/pokt-network/pocket/pull/236.

## Issue

Fixes #236

## Type of change

grep --exclude-dir='./vendor' -r -i " Delete"

- [ ] New feature, functionality or library
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Code health or cleanup
- [ ] Major breaking change
- [ ] Documentation
- [ ] Other: <REPLACE_ME>

## List of changes

- Remove all Delete Actor related 'no-op' code.

## Testing

- [x] `make test_all`
- [ ] [LocalNet](https://github.com/pokt-network/pocket/blob/main/docs/development/README.md) w/ all of the steps outlined in the `README`

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have tested my changes using the available tooling
- [ ] If applicable, I have made corresponding changes to related local or global README
- [ ] If applicable, I have added new diagrams using [mermaid.js](https://mermaid-js.github.io)
- [ ] If applicable, I have added tests that prove my fix is effective or that my feature works

2022-09-24 11:19 UTC, andrewnguyen22 requested changes

2022-09-24 11:19 UTC, andrewnguyen22 commented on persistence/docs/CHANGELOG.md
>  ## [Unreleased]
Please add `- Consolidated CHANGELOGs into one` to the PR description as well

2022-09-24 11:19 UTC, andrewnguyen22 commented on persistence/docs/CHANGELOG.md
> +## [0.0.0.0] - 2022-09-22
If you're going to move / consolidate `changelog.md` to `persistence/docs/` then `README.md` should be moved as well

2022-09-28 15:21 UTC, andrewnguyen22 commented
Just update PR to include full `list of changes` from changelog. Then it's good to go

2022-09-28 15:21 UTC, andrewnguyen22 requested changes
Just update PR to include full list of changes from changelog. Then it's good to go

2022-09-29 15:03 UTC, andrewnguyen22 commented
+ resolve conflicts  ^

2022-09-29 22:47 UTC, andrewnguyen22 commented
> Just update PR to include full list of changes from changelog. Then it's good to go

Can't approve until this is done

2022-09-29 22:47 UTC, andrewnguyen22 requested changes
> Just update PR to include full list of changes from changelog. Then it's good to go

Can't approve until this is done

2022-09-29 23:41 UTC, andrewnguyen22 approved these changes

2022-09-30 00:45 UTC, Olshansk commented
NOTE: `make develop_test` and `LocalNet` are broken on `main` so this was validated via `make test_persistence`.

2022-09-30 00:45 UTC, merged