Fix broken test on main
pokt-network/pocket pull request #259
Opened 2022-09-29 23:29 UTC by Olshansk

## Description

## Issue

Fixes #<issue_number>

## Type of change

Please mark the relevant option(s):

- [ ] New feature, functionality or library
- [x] Bug fix
- [ ] Code health or cleanup
- [ ] Major breaking change
- [ ] Documentation
- [ ] Other 

## List of changes

- Fixed broken test on main by mocking `StoreBlock` function on the persistence module in a consensus test
- Remove unused `StoreBlock` function in the utility module
- ...

## Testing

- [x] `make develop_test`
- [ ] [LocalNet](https://github.com/pokt-network/pocket/blob/main/docs/development/README.md) w/ all of the steps outlined in the `README`

## Required Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have tested my changes using the available tooling
- [ ] I have updated the corresponding CHANGELOG

### If Applicable Checklist
- [ ] I have updated the corresponding README(s); local and/or global
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added, or updated, [mermaid.js](https://mermaid-js.github.io) diagrams in the corresponding README(s)
- [ ] I have added, or updated, documentation and [mermaid.js](https://mermaid-js.github.io) diagrams in `shared/docs/*` if I updated `shared/*`README(s)

2022-09-29 23:36 UTC, andrewnguyen22 commented
Finish PR description before requesting review

2022-09-29 23:38 UTC, andrewnguyen22 requested changes

2022-09-29 23:38 UTC, andrewnguyen22 commented on utility/doc/CHANGELOG.md
> +## [0.0.0.4] - 2022-09-29
Versioning OB1?

2022-09-29 23:39 UTC, andrewnguyen22 requested changes
Versioning OB1

2022-09-29 23:39 UTC, andrewnguyen22 commented on utility/doc/CHANGELOG.md
> +## [0.0.0.4] - 2022-09-29
Versioning OB1?

2022-09-29 23:42 UTC, Olshansk commented
@andrewnguyen22 

> Finish PR description before requesting review

Sounds good. I jumped the 🔫 on this one.

2022-09-29 23:44 UTC, Olshansk commented
Versioning...

![giphy](https://user-images.githubusercontent.com/1892194/193160858-d653e2ba-14f9-42f5-add4-bb9bd54fc6f4.gif)

2022-09-30 00:52 UTC, Olshansk commented
Please note that `make develop_test` works but there is still an issue with LocalNet we're going to need to fix.

<img width="977" alt="Screen Shot 2022-09-29 at 5 51 19 PM" src="https://user-images.githubusercontent.com/1892194/193166872-fd7bf3ed-5270-45c8-88f8-660fdb427261.png">

2022-10-04 00:12 UTC, andrewnguyen22 approved these changes
@Olshansk LGTM, I realized you asked me to fix `actor_test` before merging and I did not see that until after I had merged. I planned on following up with another PR, but was wondering if you'd be able to patch that up in this PR. 

If not NBD -lmk

2022-10-04 00:23 UTC, merged

2022-10-04 00:24 UTC, Olshansk commented
@andrewnguyen22 Patched, updated, pushed, verified & merged.

2022-10-04 00:25 UTC, Olshansk commented
Also, I just misunderstood what you meant by `I realized you asked me to fix actor_test before merging`. Oddly enough `make develop_test` passed for me, so:

1. Can you submit a PR with those unit test fixes.
2. I will investigate why `make develop_test` passes

2022-10-04 17:26 UTC, andrewnguyen22 commented
@Olshansk can't reproduce the issue - seems fine

2022-10-04 23:28 UTC, Olshansk commented
@andrewnguyen22 Following up here for posterity, fix is in #282