[WIP] Stabilizing consensus
pokt-network/pocket pull request #404
Opened 2022-12-16 01:32 UTC by Olshansk

## Description

## Issue

Fixes #<issue_number>

## Type of change

Please mark the relevant option(s):

- [ ] New feature, functionality or library
- [ ] Bug fix
- [ ] Code health or cleanup
- [ ] Major breaking change
- [ ] Documentation
- [ ] Other 

## List of changes

- Change #1
- Change #2
- ...

## Testing

- [ ] `make develop_test`
- [ ] [LocalNet](https://github.com/pokt-network/pocket/blob/main/docs/development/README.md) w/ all of the steps outlined in the `README`

## Required Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have tested my changes using the available tooling
- [ ] I have updated the corresponding CHANGELOG

### If Applicable Checklist
- [ ] I have updated the corresponding README(s); local and/or global
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added, or updated, [mermaid.js](https://mermaid-js.github.io) diagrams in the corresponding README(s)
- [ ] I have added, or updated, documentation and [mermaid.js](https://mermaid-js.github.io) diagrams in `shared/docs/*` if I updated `shared/*`README(s)

2022-12-29 19:12 UTC, Olshansk commented
@gokutheengineer Just a heads up that we might have some merge conflicts. No action items or need for a review yet.

This is where I'm working through the "block is nil" issue and have been overhauling some of the logs to make things clearer to understand and debug as well. Currently thinking of ways to add better unit tests for it.

2023-01-03 22:37 UTC, Olshansk commented
@deblasis I only added @gokutheengineer as a reviewer because I don't think this requires a review from multiple people but just thought you'd appreciate seeing the change here https://github.com/pokt-network/pocket/pull/404/files#diff-351d333685b4f6a9bb38d617a69a200daa5261f20ea31a62a7f1b4123dba9520.

In particular, look at the changes in `waitForEventsInternal`. It was a bug both of us overlooked when adding deterministic testing, but works (and IMO is much clearer) now.

➕ 1️⃣  to the iteration on each other's work

2023-01-05 19:47 UTC, gokutheengineer requested changes

2023-01-05 19:47 UTC, gokutheengineer commented on consensus/pacemaker.go
>  		case <-clock.After(stepTimeout + 30*timePkg.Millisecond): // Adding 30ms to the context timeout to avoid race condition.
is there any specific reason to add exactly 30ms, or it is added because it is just enough to avoid race condition?

2023-01-09 21:09 UTC, Olshansk commented on consensus/e2e_tests/utils_test.go
>  		pocketNodes[typesCons.NodeId(i+1)] = pocketNode
#434

2023-01-09 21:13 UTC, Olshansk commented
@gokutheengineer PTAL when you have a chance

2023-01-09 22:14 UTC, Olshansk commented on consensus/debugging.go
> -	m.m.RLock()
I moved the Lock into `HandleDebugMessage()` above

2023-01-10 12:27 UTC, gokutheengineer commented
> @gokutheengineer PTAL when you have a chance

LGTM!

2023-01-10 12:27 UTC, gokutheengineer approved these changes

2023-01-10 15:37 UTC, Olshansk commented
@gokutheengineer I'm going to hold of for us to merge in #425  (already approved).

Plan is to rebase this on top of master, retest, and then submit this.

2023-01-11 00:45 UTC, merged