[WIP] State sync design overhaul - block-by-block state sync
pokt-network/pocket pull request #413
Opened 2022-12-20 23:46 UTC by Olshansk

## [WIP] Description

First implementable interface for block-by-block state sync

## Issue

Fixes #362

## Type of change

Please mark the relevant option(s):

- [x] New feature, functionality or library
- [ ] Bug fix
- [ ] Code health or cleanup
- [ ] Major breaking change
- [ ] Documentation
- [ ] Other 

## [WIP] List of changes

- Documentation update
- Interface update

## Testing

- [ ] `make develop_test`
- [ ] [LocalNet](https://github.com/pokt-network/pocket/blob/main/docs/development/README.md) w/ all of the steps outlined in the `README`

## Required Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have tested my changes using the available tooling
- [ ] I have updated the corresponding CHANGELOG

### If Applicable Checklist
- [ ] I have updated the corresponding README(s); local and/or global
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added, or updated, [mermaid.js](https://mermaid-js.github.io) diagrams in the corresponding README(s)
- [ ] I have added, or updated, documentation and [mermaid.js](https://mermaid-js.github.io) diagrams in `shared/docs/*` if I updated `shared/*`README(s)

2022-12-21 22:10 UTC, Olshansk commented
@gokutheengineer Please note that there will be implementation details in #409 that are not covered and discussed here (e.g. the local state consensus will be managing as blocks are flying in and we're processing them), so lmk if this requires any additional detail.

2022-12-29 16:30 UTC, gokutheengineer requested changes

2022-12-29 18:59 UTC, Olshansk commented on consensus/doc/PROTOCOL_STATE_SYNC.md
> +This gives a view into the data availability layer, with details of what data can be consumed from which pee (not a production interface):
```suggestion
This gives a view into the data availability layer, with details of what data can be consumed from which peer (not a production interface):
```

2022-12-29 19:00 UTC, Olshansk commented on consensus/doc/PROTOCOL_STATE_SYNC.md
> +This gives a view into the data availability layer, with details of what data can be consumed from which pee (not a production interface):
Resolved here: https://github.com/pokt-network/pocket/pull/413#discussion_r1059107713

Also, highly recommend using the "suggestion" feature available here for edits in the future:
<img width="718" alt="Screenshot 2022-12-29 at 1 59 32 PM" src="https://user-images.githubusercontent.com/1892194/209997121-25c253b0-677e-4528-ac65-c2758009e025.png">

2022-12-29 19:04 UTC, Olshansk commented on consensus/doc/PROTOCOL_STATE_SYNC.md
> +The aggregation and consumption of this peer-meta information enables the State Sync protocol by enabling the node to understand the globalized network state through sampling Peer Metadata in its loc
Is the sequenceDiagram above not sufficient? At a high level, it's: "Get peer metadata from peers," and the implementation details involve aggregating it, creating triggers, etc...

I explicitly chose to exclude it from this PR and was hoping that it's something you'd be able to add to the documentation in a couple of iterations once we get closer to designing that (after implementing the basic advertisement and retrieval) of peer metadata.

Wdyt?

2022-12-29 19:08 UTC, gokutheengineer commented on consensus/doc/PROTOCOL_STATE_SYNC.md
> +The aggregation and consumption of this peer-meta information enables the State Sync protocol by enabling the node to understand the globalized network state through sampling Peer Metadata in its loc
Okay, I will add once we have better idea.

2022-12-29 19:09 UTC, gokutheengineer approved these changes

2022-12-29 19:11 UTC, Olshansk commented on consensus/doc/PROTOCOL_STATE_SYNC.md
> +The aggregation and consumption of this peer-meta information enables the State Sync protocol by enabling the node to understand the globalized network state through sampling Peer Metadata in its loc
We can do a group design session in the future. I think that once we have the implementation for advertising & retrieving (plus the PR that Alessandro has for peer discovery), it'll be clearer.

2023-01-02 21:48 UTC, deblasis approved these changes
LGTM, just nits

2023-01-02 21:48 UTC, deblasis commented on Makefile
> +# TODO: Organize this code with a basic fo
```suggestion
# TODO: Organize this code with a basic for loop
```
?

P.S. I believe that @Gustavobelfort was looking into integrating `buf` and at that point protobuf generation would be more declarative and without all these calls. Just flagging

2023-01-02 21:48 UTC, deblasis commented on consensus/doc/PROTOCOL_STATE_SYNC.md
> +- `Block Chunk Design` - Update the singe block-by-block to be able to receive and provide multiple blocks per request.
```suggestion
- `Block Chunk Design` - Update the single block-by-block to be able to receive and provide multiple blocks per request.
```

2023-01-03 23:51 UTC, merged