[Consensus] Add Quorum Certificate to the block
pokt-network/pocket pull request #593
Opened 2023-03-17 17:33 UTC by gokutheengineer

## Description

Persisted blocks doesn't contain QC in block header field. When doing state sync, peers need the QC to validate the block. 

## Issue

## Type of change

Please mark the relevant option(s):

- [ ] New feature, functionality or library
- [X] Bug fix
- [ ] Code health or cleanup
- [ ] Major breaking change
- [ ] Documentation
- [ ] Other 

## List of changes

- Change #1
- Add quorum certificate to the block before committing in leader and replica
- Add new error `ErrNoQcInReceivedBlock` 

## Testing

- [X] `make develop_test`
- [X] [LocalNet](https://github.com/pokt-network/pocket/blob/main/docs/development/README.md) w/ all of the steps outlined in the `README`

## Required Checklist

- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added, or updated, [`godoc` format comments](https://go.dev/blog/godoc) on touched members (see: [tip.golang.org/doc/comment](https://tip.golang.org/doc/comment))
- [X] I have tested my changes using the available tooling
- [X] I have updated the corresponding CHANGELOG

### If Applicable Checklist

- [ ] I have updated the corresponding README(s); local and/or global
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added, or updated, [mermaid.js](https://mermaid-js.github.io) diagrams in the corresponding README(s)
- [ ] I have added, or updated, documentation and [mermaid.js](https://mermaid-js.github.io) diagrams in `shared/docs/*` if I updated `shared/*`README(s)

2023-03-20 23:45 UTC, Olshansk requested changes
This is a great change. My only request: can you add:

1. An empty test with a TODO to add more quorum cert validation
2. Inside of one of the existing tests where we do `require.Equal(t, uint64(1), getBlockRes.Block.GetBlockHeader().Height)`, why not validate the quorum cert dat as well?

2023-03-20 23:45 UTC, Olshansk commented on consensus/doc/CHANGELOG.md
> +- Add quorum certificate to the block before commiting to the persistence
```suggestion
- Add quorum certificate to the block before committing to persistence
```

Consider downloading grammarly.com

2023-03-20 23:45 UTC, Olshansk commented on consensus/hotstuff_leader.go
> +	commitQcBytes, err := codec.GetCodec().Marshal(commitQC)
Nice

2023-03-21 18:28 UTC, gokutheengineer commented
> 1. An empty test with a TODO to add more quorum cert validation
Done. 

> 2. Inside of one of the existing tests where we do `require.Equal(t, uint64(1), getBlockRes.Block.GetBlockHeader().Height)`, why not validate the quorum cert dat as well?
Currently persistence mock returns an almost empty whit only block height is set in blockheads. Therefore, in this PR we can't do QC validation. However, with PR https://github.com/pokt-network/pocket/pull/594, we will be able to do QC verification, as I updated test suite to generate mock blocks with valid QCs.  Wdyt?

2023-03-24 00:03 UTC, Olshansk requested changes

2023-03-24 00:03 UTC, Olshansk commented on consensus/state_sync/module.go
> +		m.logger.Error().Err(typesCons.ErrNoQcInReceivedBlock)
Add a message too

2023-03-24 00:34 UTC, Olshansk commented
@gokutheengineer It seems that you merged in these changes in #575, even though they're being reviewed here. This is not a big problem because these are small changes, but please be more careful about this in the future.

2023-03-24 20:28 UTC, gokutheengineer commented on consensus/e2e_tests/hotstuff_test.go
> +}
I added few more. I will be thinking about other potential test cases and will be updating this.

2023-03-24 23:07 UTC, Olshansk approved these changes

2023-03-25 09:52 UTC, merged