[P2P] Ensure peers refuse unencrypted connections
pokt-network/pocket pull request #598
Opened 2023-03-21 13:09 UTC by bryanchriswhite

## Description

## Issue

Fixes #<issue_number>

## Type of change

Please mark the relevant option(s):

- [ ] New feature, functionality or library
- [ ] Bug fix
- [ ] Code health or cleanup
- [ ] Major breaking change
- [ ] Documentation
- [x] Other: Regression test

## List of changes

- Added 

## Testing

- [x] `make develop_test`
- [ ] ~~[LocalNet](https://github.com/pokt-network/pocket/blob/main/docs/development/README.md) w/ all of the steps outlined in the `README`~~

## Required Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added, or updated, [`godoc` format comments](https://go.dev/blog/godoc) on touched members (see: [tip.golang.org/doc/comment](https://tip.golang.org/doc/comment))
- [ ] I have tested my changes using the available tooling
- [ ] I have updated the corresponding CHANGELOG

### If Applicable Checklist

- [ ] I have updated the corresponding README(s); local and/or global
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added, or updated, [mermaid.js](https://mermaid-js.github.io) diagrams in the corresponding README(s)
- [ ] I have added, or updated, documentation and [mermaid.js](https://mermaid-js.github.io) diagrams in `shared/docs/*` if I updated `shared/*`README(s)

2023-03-24 22:02 UTC, Olshansk requested changes
Just some NITs, but otherwise, great test!

2023-03-28 18:21 UTC, bryanchriswhite commented on p2p/transport_encryption_test.go
> +	busMock.EXPECT().GetConsensusModule().Return(mockConsensusModule).AnyTimes()
I'm not sure it's quite that straightforward. I rearranged things to try to make it more readable and group things better.

2023-03-28 21:05 UTC, dylanlott approved these changes
Looks good to me! That was a sweet freebie to get from Libp2p.

2023-04-13 21:03 UTC, Olshansk requested changes
@bryanchriswhite Seems like this PR includes the python comment search code as well and is also based against the refactor.

Can we just rebase `p2p/transport_encryption_test.go` against main?

2023-04-14 09:27 UTC, bryanchriswhite commented
> @bryanchriswhite Seems like this PR includes the python comment search code as well and is also based against the refactor.
> 
> Can we just rebase `p2p/transport_encryption_test.go` against main?

:thinking: Oops. Sorry, I'm not sure how that happened. :facepalm: 

On `main`, I checked out the test (`git checkout feat/basic-tls -- p2p/transport_encryption_test.go`) with the intention of trying to run it but I wasn't able to get past `make develop_start`:
```
go: finding module for package github.com/pokt-network/pocket/p2p/protocol
go: finding module for package github.com/pokt-network/pocket/p2p/utils
github.com/pokt-network/pocket/p2p tested by
        github.com/pokt-network/pocket/p2p.test imports
        github.com/pokt-network/pocket/p2p/protocol: no matching versions for query "latest"
github.com/pokt-network/pocket/p2p tested by
        github.com/pokt-network/pocket/p2p.test imports
        github.com/pokt-network/pocket/p2p/utils: no matching versions for query "latest"
make[1]: *** [Makefile:108: go_clean_deps] Error 1
make[1]: Leaving directory '/home/bwhite/Projects/pokt/pocket'
make: *** [Makefile:129: develop_start] Error 2
```

This change is indeed based off of #576. To resolve my mistake, I've dropped the offending commits and re-merged with the upstream branch.

2023-04-14 20:26 UTC, Olshansk approved these changes

2023-04-17 18:14 UTC, merged