Refactoring Request Body Initialization in HTTP Handlers
pokt-network/pocket pull request #742
Opened 2023-05-12 20:50 UTC by innocent-saeed36

Previously, the request bodies body were declared as value types, and then their addresses were passed to the ctx.Bind(&body) function.

In this commit, I have streamlined this process by declaring body as a pointer upfront. The ctx.Bind() function call now directly uses body without requiring the & operator.

2023-05-12 21:50 UTC, Olshansk approved these changes
Makes sense to me and happy to approve. Curious what prompted this change from you?

2023-05-12 22:02 UTC, h5law requested changes
So, I think we should either go one way or the other. Essentially this is entirely style based but I am a big fan of patterns so why not make this one consistent?

We have a few handlers that use `new()` and others that pass the `&` reference. As this PR only addresses a single instance of these we should probably update:
1) All other handlers to follow this pattern
2) Refactor the few handlers not using the `var xyz; ctx.Bind(&xyz)` pattern to use that instead.

Either way this PR will need to address more than these two lines to make everything consistent IIRC.

2023-05-13 11:57 UTC, innocent-saeed36 commented
> Makes sense to me and happy to approve. Curious what prompted this change from you?

Hi Daniel. I'm a dev beginner and I'm playing around POKT codebase. I was going through code by the help of AI and it pinpointed me this area which can be improved. I'm unfortunately incapable of helping much further from here at a current knowledge level, so I'm happy if this helped rethinking improvements on this matter throughout the entire codebase. I'm a POKT supporter in the first place. I'll be playing around POKT codebase in the future as well, so let me know if you want me to pinpoint such things for rethinking in the future or keep them for myself. Thank you and have a great day all.

2023-05-15 21:13 UTC, Olshansk commented
@innocent-saeed36 Please close this out if you don't plan to follow the recommended changes from @h5law

2023-05-17 23:38 UTC, Olshansk commented
Per @h5law's comment, going to close this out. @innocent-saeed36 If you still believe we should do this, please apply it across the whole codebase

2023-05-17 23:38 UTC, closed without merging

2023-05-18 19:32 UTC, innocent-saeed36 commented
Thanks @Olshansk for the comment. I'll not be working on it, at least not for now, but I'm happy if it open up ideas for @h5law to work on it. I'm happy if it helped in any way.