Add code review keywords for nits, techdebt, and show stoppers
pokt-network/pocket pull request #828
Opened 2023-06-15 21:15 UTC by dylanlott

## Description

reviewpad:summary

## Issue

Fixes #<issue_number>

## Type of change

Please mark the relevant option(s):

- [ ] New feature, functionality or library
- [ ] Bug fix
- [ ] Code health or cleanup
- [ ] Major breaking change
- [ ] Documentation
- [ ] Other 

## List of changes

- Change #1
- Change #2
- ...

## Testing

- [ ] `make develop_test`; if any code changes were made
- [ ] `make test_e2e` on [k8s LocalNet](https://github.com/pokt-network/pocket/blob/main/build/localnet/README.md); if any code changes were made
- [ ] `e2e-devnet-test` passes tests on [DevNet](https://pocketnetwork.notion.site/How-to-DevNet-ff1598f27efe44c09f34e2aa0051f0dd); if any code was changed
- [ ] [Docker Compose LocalNet](https://github.com/pokt-network/pocket/blob/main/docs/development/README.md); if any major functionality was changed or introduced
- [ ] [k8s LocalNet](https://github.com/pokt-network/pocket/blob/main/build/localnet/README.md); if any infrastructure or configuration changes were made

## Required Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added, or updated, [`godoc` format comments](https://go.dev/blog/godoc) on touched members (see: [tip.golang.org/doc/comment](https://tip.golang.org/doc/comment))
- [ ] I have tested my changes using the available tooling
- [ ] I have updated the corresponding CHANGELOG

### If Applicable Checklist

- [ ] I have updated the corresponding README(s); local and/or global
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added, or updated, [mermaid.js](https://mermaid-js.github.io) diagrams in the corresponding README(s)
- [ ] I have added, or updated, documentation and [mermaid.js](https://mermaid-js.github.io) diagrams in `shared/docs/*` if I updated `shared/*`README(s)

2023-06-15 21:52 UTC, Olshansk requested changes

2023-06-15 21:52 UTC, Olshansk commented on docs/development/CODE_REVIEW_GUIDELINES.md
> +Only use the above if you think normal comments / TODOs are not self explanatory enough.
```suggestion
_tl;dr Use `SOS`, `TECHDEBT(XXX)`, `TECHDEBT`, `NIT` if you think it'll help the author get context on the next steps._

When you leave reviews, if it is unclear from the reviewer to the author, please make sure to mention if:

- **NIT**: Comment is a nitpick
- **TECHDEBT**: Comment should have a TECHDEBT comment w/o a ticket
- **TECHDEBT(XXX)**: Comment should have a TECHDEBT comment but important enough that it requires a ticket to track the work in the near future
- **SOS**: Show Stopper. You feel strongly it needs to be addressed now

Only use the above if you think normal comments / TODOs are not self-explanatory enough.
```

2023-06-16 06:28 UTC, bryanchriswhite commented on docs/development/CODE_REVIEW_GUIDELINES.md
> +When you leave reviews, if it is unclear from the reviewer to the author, please make sure to mention if:
I'm struggling a bit with this sentence. Am I interpreting it correctly to be roughly equivalent to something like the following?:

```suggestion
When leaving review comments, consider if any of the following characterizations applies and prefix the comment, respectively:
```

2023-06-16 06:29 UTC, bryanchriswhite commented on docs/development/CODE_REVIEW_GUIDELINES.md
> +tl;dr Use SOS, TECHDEBT(XXX), TECHDEBT, NIT if you think it'll help the author get context on next steps.
NIT: I fee like I always see it capitalized

```suggestion
TL;DR Use SOS, TECHDEBT(XXX), TECHDEBT, NIT if you think it'll help the author get context on next steps.
```

2023-06-16 06:39 UTC, bryanchriswhite requested changes
Thanks @dylanlott! :rocket: 

It's nice to see this thing start to accumulate some more content. :raised_hands:

I feel like it could be moved closer to the section which contains the other sentence which talks about review comments specifically: "During review, submit feedback using line comments..." (i.e. a but further down). I don't think the two sentences necessarily belong right next to each other but I feel like there is a bit of a readability improvement we could get by restructuring the similar bits to be closer together. Wdyt?

2023-06-22 00:30 UTC, merged