fix: zero value nonce is invalid
pokt-network/pocket pull request #881
Opened 2023-07-05 08:29 UTC by bryanchriswhite

## Description

reviewpad:summary

## Issue

N/A; observation made while working on #732.

## Type of change

Please mark the relevant option(s):

- [ ] New feature, functionality or library
- [x] Bug fix
- [ ] Code health or cleanup
- [ ] Major breaking change
- [ ] Documentation
- [ ] Other 

## List of changes

- Adds `ErrInvalidNonce` P2P error type
- Ensures the P2P message handler rejects the zero value `Nonce` (`uint64(0)`) is invalid
- Ensures the `GetNonce` function never returns the zero value

## Testing

- [ ] `make develop_test`; if any code changes were made
- [ ] `make test_e2e` on [k8s LocalNet](https://github.com/pokt-network/pocket/blob/main/build/localnet/README.md); if any code changes were made
- [ ] `e2e-devnet-test` passes tests on [DevNet](https://pocketnetwork.notion.site/How-to-DevNet-ff1598f27efe44c09f34e2aa0051f0dd); if any code was changed
- [ ] [Docker Compose LocalNet](https://github.com/pokt-network/pocket/blob/main/docs/development/README.md); if any major functionality was changed or introduced
- [ ] [k8s LocalNet](https://github.com/pokt-network/pocket/blob/main/build/localnet/README.md); if any infrastructure or configuration changes were made

## Required Checklist

- [ ] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added, or updated, [`godoc` format comments](https://go.dev/blog/godoc) on touched members (see: [tip.golang.org/doc/comment](https://tip.golang.org/doc/comment))
- [ ] I have tested my changes using the available tooling
- [ ] I have updated the corresponding CHANGELOG

### If Applicable Checklist

- [ ] I have updated the corresponding README(s); local and/or global
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added, or updated, [mermaid.js](https://mermaid-js.github.io) diagrams in the corresponding README(s)
- [ ] I have added, or updated, documentation and [mermaid.js](https://mermaid-js.github.io) diagrams in `shared/docs/*` if I updated `shared/*`README(s)

2023-07-05 23:34 UTC, dylanlott commented on p2p/module.go
> +	if poktEnvelope.Nonce == 0 {
🤝 🙌

2023-07-05 23:35 UTC, dylanlott commented on p2p/module_test.go
Love a change with this test to code ratio 😎

2023-07-05 23:35 UTC, dylanlott commented on p2p/module_test.go
> +	t.Helper()
Nice 💯

2023-07-05 23:36 UTC, dylanlott commented on shared/crypto/rand.go
> +	if bigNonce.Uint64() == 0 {
<img src="https://media2.giphy.com/media/vvbGMpbhZMcHSsD50w/giphy.gif"/>

2023-07-06 22:19 UTC, Olshansk commented on p2p/module_test.go
There are only two types of changes in this world:
1. Lots of code w/ no tests
2. One line change w/ lots of tests

2023-07-06 22:24 UTC, Olshansk requested changes

2023-07-06 22:24 UTC, Olshansk commented on p2p/module_test.go
> +		Nonce: 0,
Can you please add another few lines in this test to make sure the default (when we don't set the nonce at all), it is also invalid?

2023-07-11 20:37 UTC, Olshansk approved these changes

2023-07-12 07:01 UTC, merged