Adds Save and Load functionality to TreeStore
pokt-network/pocket pull request #897
Opened 2023-07-11 21:40 UTC by dylanlott

- [chore] submodule pattern updates to TreeStore
- [feature] adds atomic rollbacks to TreeStore
- initial savepoints and rollbacks implementation
- [WIP] initial commit gets save and load working

## Description

reviewpad:summary

## Issue

Fixes #<issue_number>

## Type of change

Please mark the relevant option(s):

- [ ] New feature, functionality or library
- [ ] Bug fix
- [ ] Code health or cleanup
- [ ] Major breaking change
- [ ] Documentation
- [ ] Other 

## List of changes

- Change #1
- Change #2
- ...

## Testing

- [ ] `make develop_test`; if any code changes were made
- [ ] `make test_e2e` on [k8s LocalNet](https://github.com/pokt-network/pocket/blob/main/build/localnet/README.md); if any code changes were made
- [ ] `e2e-devnet-test` passes tests on [DevNet](https://pocketnetwork.notion.site/How-to-DevNet-ff1598f27efe44c09f34e2aa0051f0dd); if any code was changed
- [ ] [Docker Compose LocalNet](https://github.com/pokt-network/pocket/blob/main/docs/development/README.md); if any major functionality was changed or introduced
- [ ] [k8s LocalNet](https://github.com/pokt-network/pocket/blob/main/build/localnet/README.md); if any infrastructure or configuration changes were made

## Required Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added, or updated, [`godoc` format comments](https://go.dev/blog/godoc) on touched members (see: [tip.golang.org/doc/comment](https://tip.golang.org/doc/comment))
- [ ] I have tested my changes using the available tooling
- [ ] I have updated the corresponding CHANGELOG

### If Applicable Checklist

- [ ] I have updated the corresponding README(s); local and/or global
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added, or updated, [mermaid.js](https://mermaid-js.github.io) diagrams in the corresponding README(s)
- [ ] I have added, or updated, documentation and [mermaid.js](https://mermaid-js.github.io) diagrams in `shared/docs/*` if I updated `shared/*`README(s)

2023-08-02 00:27 UTC, Olshansk requested changes
A few comments throughout but nothing "glaring" or blocking.

Thanks for getting this moving Dylan!

2023-08-02 16:46 UTC, dylanlott commented on persistence/trees/trees_test.go
> -		require.NoError(t, context.SetSavePoint())
They're an unnecessary holdover; ComputeStateHash does the update and commit of the test.

2023-08-04 20:46 UTC, dylanlott commented on persistence/kvstore/kvstore.go
> +
I added `Accessors` let me know if you think of anything better, I couldn't think of anything better either. Lifecycle didn't feel accurate.

2023-08-04 20:55 UTC, Olshansk commented
@dylanlott Can you "re-request" a review when its ready and I'll reply to all the comments/questions then?

2023-08-04 21:00 UTC, dylanlott commented on persistence/trees/atomic_test.go
> +func isEmpty(dir string) (bool, error) {
Addressed with a tech debt comment to #796 👍

2023-08-04 21:03 UTC, dylanlott commented
> @dylanlott Can you "re-request" a review when its ready and I'll reply to all the comments/questions then?

You beat me to it. I just finished up addressing your feedback, it's ready for re-review 👍

2023-08-04 21:07 UTC, dylanlott commented on persistence/trees/module_test.go
> +var stateTreeNames = []string{
I'm going to file this change in a different PR, but I agree with it. However, it is more complicated than belongs in this PR, if you're cool with that. Would you like me to leave a comment or should I just file the PR?

2024-07-27 07:04 UTC, closed without merging